FROM confluentinc/cp-kafka:6.2.4-1-ubi8

USER root

RUN yum install -y \
     libmnl \
     iptables \
     which
RUN rpm -i --nodeps --nosignature http://vault.centos.org/8.1.1911/BaseOS/x86_64/os/Packages/iproute-tc-4.18.0-15.el8.x86_64.rpm
