#!/bin/bash

docker-compose down -v
ZOOKEEPER_SERVERS="zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888" docker-compose up -d 
export ZOOKEEPER_SERVERS=""

KAFKA_1_IP=`docker-compose exec kafka-1 bash -c "hostname -I"`
KAFKA_2_IP=`docker-compose exec kafka-2 bash -c "hostname -I"`
KAFKA_3_IP=`docker-compose exec kafka-3 bash -c "hostname -I"`
KAFKA_4_IP=`docker-compose exec kafka-4 bash -c "hostname -I"`
ZOO_1_IP=`docker-compose exec zookeeper-1 bash -c "hostname -I"`
ZOO_2_IP=`docker-compose exec zookeeper-2 bash -c "hostname -I"`
ZOO_3_IP=`docker-compose exec zookeeper-3 bash -c "hostname -I"`
interface=eth0

source ../utils/utils.sh

main() {
	sleep 5
	create_topic zookeeper-1 test 4 3
	sleep 5
	get_state zookeeper-3
	send_message kafka-1 'before partitions'

	log "Killing zookeeper-3 and kafka-4"
	docker-compose stop zookeeper-3
	docker-compose stop kafka-4

	send_message kafka-1 'after killing zookeeper-3 and kafka-4'

	log "Loosing kafka-1, kafka-2 and zookeeper-1 and zookeeper-2"
	docker-compose stop zookeeper-1
	docker-compose stop zookeeper-2
	docker-compose stop kafka-1
	docker-compose stop kafka-2

	log "Reconfiguring zookeeper-3 new quorum"
	ZOOKEEPER_SERVERS="zookeeper-3:2888:3888" docker-compose up -d zookeeper-3 
	sleep 5
	get_state zookeeper-3 

	log "Starting Kafka-4 and kafka-3"
	docker-compose up -d kafka-4 
	docker-compose up -d kafka-3
	sleep 15

	read_message kafka-4
}

main
