#!/bin/bash

source ../utils/utils.sh

docker-compose down -v
docker-compose up -d

KAFKA_1_IP=$(container_to_ip kafka-1)
KAFKA_2_IP=$(container_to_ip kafka-2)
KAFKA_3_IP=$(container_to_ip kafka-3)
KAFKA_4_IP=$(container_to_ip kafka-4)
ZOO_IP=$(container_to_ip zookeeper)

main() {

	create_topic zookeeper test 4 3
	sleep 5
	get_state zookeeper
	send_message kafka-1 'before partitions'
	read_messages kafka-1

	log "Network partition  Kafka-1, Kafka-2, Kafka-3 | Kafka-4  Zookeeper"
	block_host zookeeper $KAFKA_1_IP $KAFKA_2_IP $KAFKA_3_IP
	block_host kafka-1 $KAFKA_4_IP $ZOO_IP
	block_host kafka-2 $KAFKA_4_IP $ZOO_IP
	block_host kafka-3 $KAFKA_4_IP $ZOO_IP

	block_host kafka-4 $KAFKA_1_IP $KAFKA_2_IP $KAFKA_3_IP

	send_message kafka-1 'after partition on kafka-1 with 3 brokers'
	send_message kafka-4 'after partition on kafka-4 with 1 broker'

	get_state zookeeper

	log "Removing network partition"
	remove_partition zookeeper kafka-1 kafka-2 kafka-3 kafka-4

	sleep 15

	get_state zookeeper

	read_messages kafka-1
}

main
