#!/bin/bash

docker-compose down -v
docker-compose up -d 

KAFKA_1_IP=`docker-compose exec kafka-1 bash -c "hostname -I"`
KAFKA_2_IP=`docker-compose exec kafka-2 bash -c "hostname -I"`
KAFKA_3_IP=`docker-compose exec kafka-3 bash -c "hostname -I"`
KAFKA_4_IP=`docker-compose exec kafka-4 bash -c "hostname -I"`
ZOO_IP=`docker-compose exec zookeeper bash -c "hostname -I"`

source ../utils/utils.sh

main() {

	create_topic zookeeper test 4 3
	sleep 5
	get_state zookeeper
	send_message kafka-1 'before partitions'
	read_message kafka-1

	log "Network partition  Kafka-1, Kafka-2, Kafka-3 | Kafka-4  Zookeeper"
	block_one_host zookeeper $KAFKA_1_IP
	block_one_host zookeeper $KAFKA_2_IP
	block_one_host zookeeper $KAFKA_3_IP
	block_one_host kafka-1 $KAFKA_4_IP
	block_one_host kafka-1 $ZOO_IP
	block_one_host kafka-2 $KAFKA_4_IP
	block_one_host kafka-2 $ZOO_IP
	block_one_host kafka-3 $KAFKA_4_IP
	block_one_host kafka-3 $ZOO_IP

	block_one_host kafka-4 $KAFKA_1_IP
	block_one_host kafka-4 $KAFKA_2_IP
	block_one_host kafka-4 $KAFKA_3_IP

	send_message kafka-1 'after partition on kafka-1 with 3 brokers'
	send_message kafka-4 'after partition on kafka-4 with 1 broker'

	get_state zookeeper

	log "Removing network partition"
	remove_partition zookeeper kafka-1 kafka-2 kafka-3 kafka-4

	sleep 15

	get_state zookeeper

	read_message kafka-1
}

main
