version: "2"
services:
  zookeeper:
    build:
      context: ../
      dockerfile: Dockerfile.zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka-1:
    build:
      context: ../
      dockerfile: Dockerfile.kafka
    hostname: kafka-1
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-1:9092"
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: "1"
      KAFKA_BROKER_ID: "1"

  kafka-2:
    build:
      context: ../
      dockerfile: Dockerfile.kafka
    hostname: kafka-2
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-2:9092"
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: "1"
      KAFKA_BROKER_ID: "2"

  kafka-3:
    build:
      context: ../
      dockerfile: Dockerfile.kafka
    hostname: kafka-3
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-3:9092"
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: "1"
      KAFKA_BROKER_ID: "3"
