#!/bin/bash

docker-compose down -v
docker-compose up -d 

KAFKA_1_IP=`docker-compose exec kafka-1 bash -c "hostname -I"`
KAFKA_2_IP=`docker-compose exec kafka-2 bash -c "hostname -I"`
KAFKA_3_IP=`docker-compose exec kafka-3 bash -c "hostname -I"`
ZOO_IP=`docker-compose exec zookeeper bash -c "hostname -I"`
interface=eth0

source ../utils/utils.sh 

main() {

	create_topic zookeeper test 3 2
	get_state zookeeper
	send_message kafka-1 'before partitions'
	read_message kafka-1

	log "Network partition  Kafka-1, Kafka-2 | Kafka-3,  Zookeeper "
	docker-compose exec --privileged kafka-1 bash -c "tc qdisc add dev eth0 root netem loss 100%"

	send_message kafka-3 'should not be ok, the invalid leader'
	send_message kafka-1 'should be ok, the valid leader'

	get_state zookeeper

	log "Removing network partition"
	remove_partition zookeeper kafka-1 kafka-2 kafka-3

	sleep 15

	get_state zookeeper

	read_message kafka-1
}

main
