#!/bin/bash

source ../utils/utils.sh

docker-compose down -v
docker-compose up -d

KAFKA_1_IP=$(container_to_ip kafka-1)
KAFKA_2_IP=$(container_to_ip kafka-2)
KAFKA_3_IP=$(container_to_ip kafka-3)
KAFKA_4_IP=$(container_to_ip kafka-4)
ZOO_1_IP=$(container_to_ip zookeeper-1)
ZOO_2_IP=$(container_to_ip zookeeper-2)
ZOO_3_IP=$(container_to_ip zookeeper-3)
interface=eth0

main() {
	sleep 15
	create_topic zookeeper-1 test 4 3
	sleep 5

	get_state zookeeper-1

	send_message kafka-1 'before network outage'
	read_messages kafka-1 1

	zookeeper_mode zookeeper-1 zookeeper-2 zookeeper-3

	log 'Network outage starts'

    block_host kafka-1 $KAFKA_2_IP $KAFKA_3_IP $KAFKA_4_IP $ZOO_1_IP $ZOO_2_IP $ZOO_3_IP
    block_host kafka-2 $KAFKA_1_IP $KAFKA_3_IP $KAFKA_4_IP $ZOO_1_IP $ZOO_2_IP $ZOO_3_IP
    block_host kafka-3 $KAFKA_1_IP $KAFKA_2_IP $KAFKA_4_IP $ZOO_1_IP $ZOO_2_IP $ZOO_3_IP
    block_host kafka-4 $KAFKA_1_IP $KAFKA_2_IP $KAFKA_3_IP $ZOO_1_IP $ZOO_2_IP $ZOO_3_IP
    block_host zookeeper-1 $ZOO_2_IP $ZOO_3_IP
    block_host zookeeper-2 $ZOO_1_IP $ZOO_3_IP
    block_host zookeeper-3 $ZOO_2_IP $ZOO_2_IP

	log "Let's wait for the timeouts to occur"
	sleep 45

	zookeeper_mode zookeeper-1 zookeeper-2 zookeeper-3

	log 'Network outage ends'
	remove_partition kafka-1 kafka-2 kafka-3 kafka-4 zookeeper-1 zookeeper-2 zookeeper-3

	log 'Waiting for the system to recover'
	sleep 45

	get_state zookeeper-1
	zookeeper_mode zookeeper-1 zookeeper-2 zookeeper-3


	send_message kafka-1 'after network outage'
	read_messages kafka-1 2
}

main
